[prod]
SECRET_GOOGLE_DRIVE_API_KEY = 'gAAAAABj8EJl8OFGF91PtN070Vm0_sLsxZxKk9yvoI9sePQs24gXPoK8NsUdm2kFCHoY1sFRzVb46gRmkyWArIwf_Mb5bOHaTUhGjixY1gecrskx1jOUKS59LkuTROMhjmoAGq_lllp2'
SECRET_AWS_ACCESS_KEY = 'gAAAAABj8ZD1hKxtOdN3NIdYWD05B4Heo92r1hehEp0ip6kvqheFib-XqAcrjWIIQbeOOSa97CkulknzRC6iBHHTNCv3y79TYfxPBx-D1P4RDZ9-KwzqDxM='
SECRET_AWS_SECRET_ACCESS_KEY = 'gAAAAABj8ZEC2s-7MtlxqrdGsYGUsw6z4mTm8XWUOdGHGQXenHDfF6z_elLX-EFEhPm5E9TEXPS4HqpD9WVqOAVGsdy6Xw7eSX73xnMpk4tM3n1GpD2PhVtABmqHE1aCq_2yz-ICOKiX'

[dev]
